name: sqlcool2
description: Easy and reactive Sqlite. Stream of changes, select bloc, custom database models
homepage: https://github.com/synw/sqlcool2
version: 2.0.0 # Upgrade de versão para indicar breaking changes

environment:
  sdk: ">=3.0.0 <4.0.0" # Compatível com Flutter 3.x

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.0
  sqflite: ^2.3.0
  synchronized: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  extra_pedantic: ^4.0.0

flutter:
  uses-material-design: true